require_relative 'installer_apt'
require_relative 'installer_dnf'
require_relative 'installer_yum'
require_relative 'installer_eopkg'
require_relative 'installer_pacman'
require_relative 'installer_alpine'
require_relative 'installer_gentoo'
require_relative 'installer_brew'
